build-dac:
  stage: build
  tags: [macos-arm64]
  variables:
    qtpath: /Users/gitlab/Qt/${QT_VERSION}/macos/bin
  script:
    - !reference [.get-gams]
    - !reference [.gams-folder-dac]
    - printf "GAMS_DISTRIB=$HOME/cache/gams-installs/`cat gams_folder_dac.txt`\n" > gamsinclude.pri
    - printf "GAMS_DISTRIB_C_API=\$\$GAMS_DISTRIB/apifiles/C/api\n" >> gamsinclude.pri
    - printf "GAMS_DISTRIB_CPP_API=\$\$GAMS_DISTRIB/apifiles/C++/api\n" >> gamsinclude.pri
    - mkdir build && cd build
    - GAMS_CORE_PATH="${GAMS_FOR_MACOS}"
    - PATH="${qtpath}:${GAMS_FOR_MACOS}:${PATH}"
    - qmake ../gams-mii.pro CONFIG+=release && make -j4
  needs: [fetch-ci-scripts]
  artifacts:
    name: mii-dac
    expire_in: 2 hours
    paths: [build]

build-deg:
  stage: build
  tags: [macos]
  variables:
    qtpath: /Users/gitlab/Qt/${QT_VERSION}/macos/bin
  script:
    - !reference [.get-gams]
    - !reference [.gams-folder-deg]
    - printf "GAMS_DISTRIB=$HOME/cache/gams-installs/`cat gams_folder_deg.txt`\n" > gamsinclude.pri
    - printf "GAMS_DISTRIB_C_API=\$\$GAMS_DISTRIB/apifiles/C/api\n" >> gamsinclude.pri
    - printf "GAMS_DISTRIB_CPP_API=\$\$GAMS_DISTRIB/apifiles/C++/api\n" >> gamsinclude.pri
    - mkdir build && cd build
    - GAMS_CORE_PATH="${GAMS_FOR_MACOS}"
    - PATH="${qtpath}:${GAMS_FOR_MACOS}:${PATH}"
    - qmake ../gams-mii.pro CONFIG+=release && make -j4
  needs: [fetch-ci-scripts]
  artifacts:
    name: mii-deg
    expire_in: 2 hours
    paths: [build]

build-leg:
  stage: build
  tags: [linux]
  image:
    name: $GAMS_CONTAINER_REGISTRY/qt-machines/leg/${QT_IMAGE_VERSION}:latest
    entrypoint: [""]   # prevent startup.sh
  needs: [fetch-ci-scripts]
  variables:
    DOLLAR_GAMS: $$$$GAMS_DISTRIB
  script:
    - !reference [.get-gams]
    - !reference [.gams-folder-leg]
    - echo "GAMS_DISTRIB=/cache/gams-installs/`cat gams_folder_leg.txt`" > gamsinclude.pri
    - echo "GAMS_DISTRIB_C_API=$DOLLAR_GAMS/apifiles/C/api" >> gamsinclude.pri
    - echo "GAMS_DISTRIB_CPP_API=$DOLLAR_GAMS/apifiles/C++/api" >> gamsinclude.pri
    - mkdir build && cd build
    - qmake ../gams-mii.pro CONFIG+=release && make -j4
  artifacts:
    name: mii-leg
    expire_in: 2 hours
    paths: [build]

build-wei:
  stage: build
  tags: [windows]
  needs: [fetch-ci-scripts]
  variables:
     cmd_vcvars: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat
  image:
    name: $GAMS_CONTAINER_REGISTRY/qt-machines/wei/${QT_IMAGE_VERSION}:latest
  script:
    - !reference [.get-gams-wei]
    - !reference [.gams-folder-wei]
    - '& $cmd_vcvars'
    - $data = 
      "GAMS_DISTRIB=C:/Cache/gams-installs/$(Get-Content mygmsdir.tmp -Raw)",
      'GAMS_DISTRIB_C_API=$$GAMS_DISTRIB/apifiles/C/api',
      'GAMS_DISTRIB_CPP_API=$$GAMS_DISTRIB/apifiles/C++/api'
    - $data | out-file -encoding ascii gamsinclude.pri
    - mkdir build
    - cd build
    - qmake ..\gams-mii.pro "CONFIG+=release"
    - nmake
  artifacts:
    name: mii-wei
    expire_in: 2 hours
    paths: [build]

build-wei-debug:
  stage: build
  rules:
    - if: $PF_WEI_DEBUG == "0"
      when: never
    - when: on_success
  tags: [windows]
  needs: [fetch-ci-scripts]
  variables:
     cmd_vcvars: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat
  image:
    name: $GAMS_CONTAINER_REGISTRY/qt-machines/wei/${QT_IMAGE_VERSION}:latest
  script:
    - !reference [.get-gams-wei]
    - !reference [.gams-folder-wei]
    - '& $cmd_vcvars'
    - $data = 
      "GAMS_DISTRIB=C:/Cache/gams-installs/$(Get-Content mygmsdir.tmp -Raw)",
      'GAMS_DISTRIB_C_API=$$GAMS_DISTRIB/apifiles/C/api',
      'GAMS_DISTRIB_CPP_API=$$GAMS_DISTRIB/apifiles/C++/api'
    - $data | out-file -encoding ascii gamsinclude.pri
    - mkdir build
    - cd build
    - qmake ..\gams-mii.pro "CONFIG+=debug"
    - nmake
  artifacts:
    name: mii-wei-debug
    expire_in: 2 hours
    paths: [build]
